include:
  local: HAWKSCAN_LOCAL.gitlab-ci.yml

variables:
  HAWK_APP_IMAGE: $CI_REGISTRY_IMAGE
  HAWK_APP_SVC_NAME: vuln-django
  HAWK_APP_PORT: 8020
  HAWKSCAN_ARGS: "stackhawk.yml stackhawk-gitlab.yml"

stages:
  - test
  - build
  - hawkscan

docker-build:
  stage: build
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
  script:
   - env
   - docker build -t $HAWK_APP_IMAGE .
   - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
   - docker push $HAWK_APP_IMAGE
